checker:
  print_fail: false
  print_ms_hit: false
  retries: 1
  timeout: 6000
  threads: 30
  save_bad: false
  display_mode: cn
  import_from_file: false
  webhook:
    Webhook: true
    WebhookID: https://discord.com/api/webhooks/1279781598946136206/XxGwMX5EcGPLc-bo2gHi0pE8zOCWJDYISF5GMJMO-ZlDFb4pX1i9T5iTC6LVL9YVIMfy
  proxy:
    proxy: false
    proxy_type: HTTP
    proxy_api: false
    api_link: 
