checker:
  print_fail: false
  print_ms_hit: false
  retries: 1
  timeout: 6000
  threads: 30
  save_bad: false
  display_mode: cn
  import_from_file: false
  webhook:
    Webhook: true
    WebhookID: https://discord.com/api/webhooks/
  proxy:
    proxy: false
    proxy_type: HTTP
    proxy_api: false
    api_link: 
